/**
 * Hevy exercise catalog: data + lookups.
 *
 * Isomorphic — imported by both server routes and client components
 * (e.g. ExercisePickerDropdown). Must NOT import server-only code, even
 * dynamically (Turbopack graph-walks `await import()` for client SSR).
 */

import { Exercise } from "../types";

// Generated by `npm run refresh:hevy` (scripts/refresh-hevy-catalog.ts).
// Refresh runs as the `prebuild` step so the bundled catalog always
// reflects the latest Hevy templates plus the developer's custom
// exercises at build time.
import catalog from "../data/hevy-exercises/catalog.json";

export interface HevyExerciseTemplate {
  id: string;
  title: string;
  type: string;
  primary_muscle_group: string;
  secondary_muscle_groups: string[];
  equipment: string;
  is_custom: boolean;
}

const allHevyExercises: HevyExerciseTemplate[] =
  catalog.exercise_templates as HevyExerciseTemplate[];

// Hevy exposes a few set-shape variants beyond the four our UI handles. Normalize
// here so the rest of the app can keep its narrow Exercise["type"] union.
// `bodyweight_weighted` (e.g. Weighted Pull-Up, Sit Up (Weighted)) accepts
// weight_kg + reps, identical to weight_reps for sync purposes.
function normalizeHevyType(t: string): Exercise["type"] {
  if (t === "bodyweight_weighted") return "weight_reps";
  return t as Exercise["type"];
}

export function convertHevyToExercise(hevy: HevyExerciseTemplate): Exercise {
  return {
    id: hevy.id,
    title: hevy.title,
    type: normalizeHevyType(hevy.type),
    primary_muscle_group: hevy.primary_muscle_group,
    secondary_muscle_groups: hevy.secondary_muscle_groups,
    is_custom: hevy.is_custom,
  };
}

export const HEVY_EXERCISES = allHevyExercises;

const exerciseIdToPosition = new Map<string, number>();
const exerciseIdToTemplate = new Map<string, HevyExerciseTemplate>();
HEVY_EXERCISES.forEach((ex, i) => {
  exerciseIdToPosition.set(ex.id, i);
  exerciseIdToTemplate.set(ex.id, ex);
});

export function getHevyTemplateById(id: string): HevyExerciseTemplate | null {
  return exerciseIdToTemplate.get(id) ?? null;
}

export function getExerciseCount(): number {
  return HEVY_EXERCISES.length;
}

export function getExerciseStats() {
  const official = HEVY_EXERCISES.filter((ex) => !ex.is_custom).length;
  const custom = HEVY_EXERCISES.filter((ex) => ex.is_custom).length;
  return { total: HEVY_EXERCISES.length, official, custom };
}

export function getExerciseById(id: string): Exercise | null {
  const hevy = exerciseIdToTemplate.get(id);
  return hevy ? convertHevyToExercise(hevy) : null;
}

export function getExercisesByMuscleGroup(muscleGroup: string): HevyExerciseTemplate[] {
  return HEVY_EXERCISES.filter(
    (ex) =>
      ex.primary_muscle_group.toLowerCase() === muscleGroup.toLowerCase() ||
      ex.secondary_muscle_groups.some(
        (mg) => mg.toLowerCase() === muscleGroup.toLowerCase(),
      ),
  );
}

export function getExercisesByEquipment(equipment: string): HevyExerciseTemplate[] {
  return HEVY_EXERCISES.filter(
    (ex) => ex.equipment.toLowerCase() === equipment.toLowerCase(),
  );
}

export function getExercisePosition(id: string): number | undefined {
  return exerciseIdToPosition.get(id);
}

console.log(`📊 Hevy Exercise Database Loaded:`);
const stats = getExerciseStats();
console.log(`   Total: ${stats.total} exercises`);
console.log(`   Official: ${stats.official}`);
console.log(`   Custom: ${stats.custom}`);
if (typeof catalog.generated_at === "string") {
  console.log(`   Snapshot: ${catalog.generated_at}`);
}
